# Generated by Django 2.1.2 on 2018-10-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phonemunber',
            new_name='phonenumber',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Horror', 'Horror'), ('Romentic', 'Romentic'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='releasedate',
            field=models.DateField(),
        ),
    ]
